

import { StyleSheet } from "react-native";
import { fontFamily } from "../typography";
import colors from '@/app/theme/colors';

export const getDashboardStyles = (t: typeof colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: t.neutral.lightest,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  welcomeSection: {
    marginBottom: 32,
    paddingTop: 8,
  },
  welcomeTitle: {
    fontFamily: fontFamily.satoshi,
    fontSize: 28,
    fontWeight: '400',
    color: t.neutral.darkest,
    lineHeight: 36,
    marginBottom: 8,
  },
  userName: {
    fontFamily: fontFamily.satoshiBold,
    fontWeight: '700',
  },
  welcomeSubtitle: {
    fontFamily: fontFamily.satoshi,
    fontSize: 16,
    color: t.neutral.medium,
    lineHeight: 22,
  },
  section: {
    marginBottom: 32,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 18,
    fontWeight: '600',
    color: t.neutral.darkest,
  },
  viewAllButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: t.neutral.lighter,
    borderRadius: 6,
  },
  viewAllText: {
    fontFamily: fontFamily.satoshiMedium,
    fontSize: 14,
    color: t.neutral.medium,
    fontWeight: '500',
  },
  // Quick Actions - Smaller, more compact design
  actionGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingTop: 16,
  },
  actionCard: {
    backgroundColor: t.neutral.lighter,
    padding: 16,
    borderRadius: 10,
    alignItems: 'center',
    flex: 1,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  actionText: {
    marginTop: 8,
    fontFamily: fontFamily.satoshiMedium,
    fontSize: 13,
    fontWeight: '500',
    color: t.neutral.darkest,
    textAlign: 'center',
  },
  actionIcon: {
    width: 24,
    height: 24,
  },
  actionIconContainer: {
    width: 36,
    height: 36,
    backgroundColor: t.neutral.lightest,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Session Cards
  sessionCard: {
    backgroundColor: t.neutral.lightest,
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  sessionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sessionInfo: {
    flex: 1,
  },
  sessionTitle: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 16,
    fontWeight: '600',
    color: t.neutral.darkest,
    marginBottom: 4,
  },
  sessionSubtitle: {
    fontFamily: fontFamily.satoshi,
    fontSize: 14,
    color: t.neutral.medium,
  },
  continueButton: {
    backgroundColor: t.brand.primary,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  continueButtonText: {
    fontFamily: fontFamily.satoshiBold,
    color: t.neutral.lightest,
    fontSize: 14,
    fontWeight: '600',
  },
  breakdownContainer: {
    marginTop: 16,
  },
  breakdownHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  breakdownTitle: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    letterSpacing: 0.5,
  },
  breakdownTotal: {
    fontFamily: fontFamily.satoshi,
    fontSize: 14,
    color: '#6C757D',
  },
  chartContainer: {
    marginBottom: 16,
  },
  chart: {
    flexDirection: 'row',
    height: 8,
    backgroundColor: t.neutral.lighter,
    borderRadius: 4,
    overflow: 'hidden',
  },
  chartSegment: {
    borderRadius: 4,
  },
  chartLabel: {
    fontFamily: fontFamily.satoshiLight,
    fontSize: 12,
    color: t.neutral.medium,
    textAlign: 'center',
    marginTop: 6,
  },
  breakdownList: {
    marginTop: 12,
  },
  breakdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: t.neutral.lighter,
  },
  breakdownItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  breakdownItemIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  breakdownItemName: {
    fontFamily: fontFamily.satoshiMedium,
    fontSize: 14,
    fontWeight: '500',
    color: t.neutral.darkest,
  },
  breakdownItemStats: {
    alignItems: 'flex-end',
  },
  breakdownItemPercentage: {
    fontFamily: fontFamily.satoshiLight,
    fontSize: 12,
    color: t.neutral.medium,
    marginBottom: 2,
  },
  breakdownItemCount: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 13,
    fontWeight: '600',
    color: t.neutral.medium,
  },
  // Stats Grid
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingTop: 16,
  },
  statCard: {
    backgroundColor: t.neutral.lightest,
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
    flex: 1,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  statNumber: {
    fontFamily: fontFamily.satoshiBlack,
    fontSize: 24,
    fontWeight: '700',
    color: t.neutral.medium,
    marginBottom: 4,
  },
  statLabel: {
    fontFamily: fontFamily.satoshiMedium,
    fontSize: 12,
    color: t.neutral.medium,
    textAlign: 'center',
    fontWeight: '500',
  },
  // Empty State
  emptyState: {
    alignItems: 'center',
    paddingVertical: 48,
    backgroundColor: t.neutral.lightest,
    borderRadius: 12,
    marginTop: 24,
    borderWidth: 1,
    borderColor: t.neutral.light,
  },
  emptyStateTitle: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 20,
    fontWeight: '600',
    color: t.neutral.darkest,
    marginTop: 16,
    marginBottom: 8,
  },
  emptyStateText: {
    fontFamily: fontFamily.satoshi,
    fontSize: 16,
    color: t.neutral.medium,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
  },
  startNewButton: {
    backgroundColor: t.brand.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  startNewButtonText: {
    fontFamily: fontFamily.satoshiBold,
    color: t.neutral.lightest,
    fontSize: 16,
    fontWeight: '600',
  },
  // Legacy styles (keeping for compatibility)
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: t.neutral.light,
    marginBottom: 24,
  },
  title: {
    fontFamily: fontFamily.satoshiBlack,
    fontSize: 28,
    fontWeight: "700",
    color: t.neutral.darkest,
    marginBottom: 8,
    lineHeight: 34,
  },
  subtitle: {
    fontFamily: fontFamily.satoshi,
    fontSize: 16,
    color: t.neutral.medium,
    textAlign: "center",
    lineHeight: 22,
  },
  card: {
    backgroundColor: t.neutral.lightest,
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 18,
    fontWeight: "600",
    color: t.neutral.darkest,
    marginBottom: 12,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  legacyStatLabel: {
    fontFamily: fontFamily.satoshiMedium,
    fontSize: 14,
    color: t.neutral.medium,
    fontWeight: "500",
  },
  statValue: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 14,
    color: t.neutral.darkest,
    fontWeight: "600",
  },
  primaryButton: {
    backgroundColor: t.brand.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginTop: 16,
  },
  primaryButtonText: {
    fontFamily: fontFamily.satoshiBold,
    color: t.neutral.lightest,
    fontSize: 16,
    fontWeight: "600",
  },
  secondaryButton: {
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: t.brand.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginTop: 12,
  },
  secondaryButtonText: {
    fontFamily: fontFamily.satoshiBold,
    color: t.brand.primary,
    fontSize: 16,
    fontWeight: "600",
  },
  floatingButton: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: t.brand.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  statusBadge: {
    backgroundColor: t.neutral.lighter,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  statusBadgeText: {
    color: t.brand.primary,
    fontSize: 12,
    fontWeight: "600",
  },
});

// Backward-compatible static export
export const dashboardStyles = getDashboardStyles(colors);